[package]
name = "aftereffects"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

[features]
default = ["algebra-nalgebra"]
#algebra-cgmath = ["cgmath"]
#algebra-mint = ["mint"]
algebra-nalgebra = ["nalgebra"]

[dependencies]
aftereffects-sys = "*"
function_name = "0.2.0"
num_enum = "0.4.3"
#cgmath = { version = "^0.17.0", optional = true }
#mint = { version = "^0.5.0", optional = true }
nalgebra = { version = "0.21.0", optional = true }
widestring = "0.4.0"

[dev-dependencies]
cargo-husky = "1.5.0"

[profile.test]
default = ["algebra-nalgebra"]
