[package]
name = "aftereffects"
version = "0.1.6"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

[features]
default = ["algebra-nalgebra"]
#algebra-cgmath = ["cgmath"]
#algebra-mint = ["mint"]
algebra-nalgebra = ["nalgebra"]

[dependencies]
aftereffects-sys = { path = "../aftereffects-sys" }
bitflags = "1.2.1"
function_name = "0.2.0"
nalgebra = { version = "0.22.0", optional = true }
num_enum = "0.5.1"
#cgmath = { version = "^0.17.0", optional = true }
#mint = { version = "^0.5.0", optional = true }
widestring = "0.4.3"

[profile.test]
default = ["algebra-nalgebra"]
