[package]
name = "aftereffects"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aftereffects-sys = { path = "../aftereffects-sys" }
num_enum = { git = "https://github.com/Dentosal/num_enum_simplified" }
# casey = ">=0.2.0"
