[package]
name = "aftereffects"
version = "0.1.6"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

[features]
default = ["algebra-nalgebra"]
#algebra-cgmath = ["cgmath"]
#algebra-mint = ["mint"]
algebra-nalgebra = ["nalgebra"]

[dependencies]
aftereffects-sys = { path = "../aftereffects-sys" }
bincode = "1.3.1"
bitflags = "1.2.1"
c_vec = "2.0.0"
function_name = "0.2.0"
nalgebra = { version = "0.23.0", optional = true }
num_enum = "0.5.1"
#cgmath = { version = "^0.17.0", optional = true }
#mint = { version = "^0.5.0", optional = true }
serde = { version = "1.0.117", features = ["derive"] }
#serde_cbor = "0.11.1"
serde_json = "1.0.59"
widestring = "0.4.3"

[profile.test]
default = ["algebra-nalgebra"]
