[package]
name = "aftereffects"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"

[features]
default = ["algebra-nalgebra"]
#algebra-cgmath = ["cgmath"]
#algebra-mint = ["mint"]
algebra-nalgebra = ["nalgebra"]

[dependencies]
aftereffects-sys = { path = "../aftereffects-sys" }
num_enum = { git = "https://github.com/Dentosal/num_enum_simplified" }
#cgmath = { version = "^0.17.0", optional = true }
#mint = { version = "^0.5.0", optional = true }
nalgebra = { version = "^0.20.0", optional = true }

[profile.test]
default = ["algebra-nalgebra"]
