[package]
name = "premiere"
version = "0.0.1"
authors = ["Moritz Moeller <virtualritz@protonmail.com>", "Adrian <adrian.eddy@gmail.com>"]
license = "Apache-2.0 OR BSD-3-Clause OR MIT OR Zlib"
edition = "2021"
exclude = [".github/**/*", "crates/**/*"]
description = "High(er) level bindings for the Adobe Premiere® SDK."
keywords = ["motion-graphics", "premiere", "graphics", "plugins"]
categories = ["graphics", "multimedia::video", "rendering::graphics-api"]
readme = "README.md"
homepage = "https://developer.adobe.com/console/servicesandapis/pr"
repository = "https://github.com/virtualritz/after-effects/"

[dependencies]
premiere-sys = { path = "../premiere-sys" }
bincode = "1.3.3"
bitflags = "2.4.2"
c_vec = "2.0.0"
nalgebra = { version = "0.32.3", optional = true }
ultraviolet = { version = "0.9.2", features = [ "f64" ], optional = true }
num_enum = "0.7.2"
num-traits = "0.2.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
widestring = "1.0.2"
log = "0.4"
cstr-literal = "0.1"
paste = "1"
parking_lot = "0.12"
fastrand = "2.0"
hash32 = "0.3"
mucow = "0.1"
base64 = "0.21"
